name: Create and publish a Docker image

on:
  push:
    branches:
        - github-actions-practice

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check .editorconfig
        uses: actions/setup-python@v3
        # with:
        #     python-version:3.x
        # run: |
        #     pip install editorconfig-checker
        #     editorconfig-checker

      - name: Run Python linter - pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: Run Python linter - black
        uses: psf/black@stable

      - name: Run markdown linter
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md

    #   - name: Login to Docker Hub
    #     run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #     env:
    #       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    #   - name: Build and push Docker image
    #     run: |
    #       docker build -t m4ster0fdis4ster/nginx-homework:latest .
    #       docker push m4ster0fdis4ster/nginx-homework:latest
    #     env:
    #       DOCKER_BUILDKIT: 1


